### PR TITLE
Fix Drupal 10.3 failures, fixes #41, fixes #46

### LINKED ISSUE #41: With Drupal 10.3+: the requested URL returned error: 500
Hi,

I'm finding that the latest version of Drupal this works with is 10.2. It seems to be down to [#3240792](https://www.drupal.org/node/3240792) (see [comment #63](https://www.drupal.org/project/drupal/issues/3240792#comment-15481821) onwards).

The following passes when `$branch` is `10.2.x` but fails with `10.3.x`.

```sh
git clone --depth 1 https://git.drupalcode.org/project/drupal -b $branch
cd drupal
ddev delete -Oy test-drupal || true
ddev config --project-name=test-drupal --php-version=8.1 --web-environment-add SYMFONY_DEPRECATIONS_HELPER=disabled
ddev start -y
ddev composer -n require "drupal/core-dev:^10"
ddev get ddev/ddev-selenium-standalone-chrome
ddev restart
ddev exec "curl -v selenium-chrome:4444/wd/hub/status"
ddev exec -d /var/www/html "vendor/bin/phpunit -v -c ./core/phpunit.xml.dist ./core/modules/system/tests/src/FunctionalJavascript/FrameworkTest.php"
```

As a workaround I'm using https://raw.githubusercontent.com/ddev/ddev-contrib/master/docker-compose-services/drupalci-chromedriver/docker-compose.chromedriver.yaml which uses `drupalci/webdriver-chromedriver:production`.

Thanks!

### LINKED ISSUE #46: Automated tests are failing on both stable and DDEV HEAD
All tests seem to be failing night after night:

https://github.com/ddev/ddev-selenium-standalone-chrome/actions

### PR DESCRIPTION
**Pull request by rfay**
## The Issue

This is @andriokha 's recommended fix from 
* #41

I'm baffled why he didn't present it as a PR, but here it is, showing co-author.

It seems to solve the test problem

Fixes
* #41
* #46 

Manual testing:

`ddev get https://github.com/rfay/ddev-selenium-standalone-chrome/tarball/20240703_andriokha_fix_drupal_10.3`

### CODE REVIEW

**Comment by rfay** [comment]
And tests are green. Manual testing recommended of course.

`ddev get https://github.com/rfay/ddev-selenium-standalone-chrome/tarball/20240703_andriokha_fix_drupal_10.3`

**Comment by andriokha** [comment]
Thanks @rfay! As mentioned in https://github.com/ddev/ddev-selenium-standalone-chrome/issues/41#issuecomment-2068064384 I wasn't sure if the problem was best fixed by a change here or in `lullabot/php-webdriver`. As of today [there's an open PR against the latter](https://github.com/Lullabot/php-webdriver/pull/10), so it might be worth holding off merging this in until that's resolved (if it gets merged in, we shouldn't need any change to this, and this will carry on working with older versions of Drupal as well).

**Comment by andriokha** [comment]
Note that PR's been merged now, so hopefully the tests will start running green without any changes required and we can close this.

**Comment by rfay** [comment]
Tests are green now, https://github.com/ddev/ddev-selenium-standalone-chrome/actions

**Pull request closed without merging**
